plugins:
  - '@typescript-eslint'
  - prettier
  - react

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - prettier/react

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
  sourceType: module
  project: ./tsconfig.json

env:
  node: true
  es2020: true

settings:
  react:
    version: detect

rules:
  no-dupe-class-members: off
  no-redeclare: off
  prettier/prettier: warn
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/class-name-casing': off
